### PR TITLE
Persist service after first request 

### PR DESCRIPTION
**Pull request by Mic92**
We still have the advantage of zero downtime restarts but given this is on the only service on the machine we can just run it all the time

### CODE REVIEW

**Comment by Mic92** [comment]
@mergify queue

**Comment by Mic92** [comment]
@mergify rebase

**Comment by Mic92** [comment]
@mergify queue

**Comment by Mic92** [comment]
cc @Lassulus

**Review by Lassulus — APPROVED** [review]

**Comment by Lassulus** [comment]
@mergify rebase

**Pull request merged**
